<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="14" ignored="0" total="24" passed="10">
  <reporter-output>
  </reporter-output>
  <suite name="futureloan" duration-ms="9942" started-at="2020-08-14T12:51:39Z" finished-at="2020-08-14T12:51:49Z">
    <groups>
    </groups>
    <test name="注册接口" duration-ms="5160" started-at="2020-08-14T12:51:39Z" finished-at="2020-08-14T12:51:44Z">
      <class name="com.lemon.cases.RegisterCase">
        <test-method status="PASS" signature="beforeClass(int)[pri:0, instance:com.lemon.cases.RegisterCase@8a589a2]" name="beforeClass" is-config="true" duration-ms="33" started-at="2020-08-14T20:51:39Z" finished-at="2020-08-14T20:51:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.RegisterCase@8a589a2]" name="test" duration-ms="1245" started-at="2020-08-14T20:51:40Z" data-provider="datas" finished-at="2020-08-14T20:51:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=1, name='register', method='post', url='http://api.lemonban.com/futureloan/member/register', params='{"mobile_phone":"19000000000","pwd":""}', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='null'}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [PASSED] but found [FAILED]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.lemon.cases.RegisterCase.test(RegisterCase.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="FAIL" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.RegisterCase@8a589a2]" name="test" duration-ms="147" started-at="2020-08-14T20:51:42Z" data-provider="datas" finished-at="2020-08-14T20:51:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=2, name='register', method='post', url='http://api.lemonban.com/futureloan/member/register', params='{"mobile_phone":"","pwd":"123456"}', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='null'}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [PASSED] but found [FAILED]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.lemon.cases.RegisterCase.test(RegisterCase.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="FAIL" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.RegisterCase@8a589a2]" name="test" duration-ms="148" started-at="2020-08-14T20:51:42Z" data-provider="datas" finished-at="2020-08-14T20:51:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=3, name='register', method='post', url='http://api.lemonban.com/futureloan/member/register', params='{"mobile_phone":"123","pwd":"123456123"}', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='null'}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [PASSED] but found [FAILED]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.lemon.cases.RegisterCase.test(RegisterCase.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="FAIL" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.RegisterCase@8a589a2]" name="test" duration-ms="141" started-at="2020-08-14T20:51:42Z" data-provider="datas" finished-at="2020-08-14T20:51:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=4, name='register', method='post', url='http://api.lemonban.com/futureloan/member/register', params='{"mobile_phone":"19000000000","pwd":"12345"}', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='null'}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [PASSED] but found [FAILED]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.lemon.cases.RegisterCase.test(RegisterCase.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.RegisterCase@8a589a2]" name="test" duration-ms="1032" started-at="2020-08-14T20:51:42Z" data-provider="datas" finished-at="2020-08-14T20:51:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=5, name='register', method='post', url='http://api.lemonban.com/futureloan/member/register', params='{"mobile_phone":"17817620985","pwd":"12345678"}', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='select count(*) from member a where a.mobile_phone = '17817620985';'}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="FAIL" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.RegisterCase@8a589a2]" name="test" duration-ms="575" started-at="2020-08-14T20:51:43Z" data-provider="datas" finished-at="2020-08-14T20:51:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=6, name='register', method='post', url='http://api.lemonban.com/futureloan/member/register', params='{"mobile_phone":"17817620985","pwd":"12345678"}', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='select count(*) from member a where a.mobile_phone = '17817620985';'}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [PASSED] but found [FAILED]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.lemon.cases.RegisterCase.test(RegisterCase.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- com.lemon.cases.RegisterCase -->
    </test> <!-- 注册接口 -->
    <test name="登录接口" duration-ms="1097" started-at="2020-08-14T12:51:44Z" finished-at="2020-08-14T12:51:45Z">
      <class name="com.lemon.cases.LoginCase">
        <test-method status="PASS" signature="beforeClass(int)[pri:0, instance:com.lemon.cases.LoginCase@3f19b8b3]" name="beforeClass" is-config="true" duration-ms="1" started-at="2020-08-14T20:51:44Z" finished-at="2020-08-14T20:51:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.LoginCase@3f19b8b3]" name="test" duration-ms="143" started-at="2020-08-14T20:51:44Z" data-provider="datas" finished-at="2020-08-14T20:51:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=1, name='login', method='post', url='http://api.lemonban.com/futureloan/member/login', params='{"mobile_phone":"19000000000","pwd":""}', contentType='json', expectedResult='{"$.code":1,"$.msg":"密码为空"}', sql='null'}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="FAIL" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.LoginCase@3f19b8b3]" name="test" duration-ms="141" started-at="2020-08-14T20:51:44Z" data-provider="datas" finished-at="2020-08-14T20:51:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=2, name='login', method='post', url='http://api.lemonban.com/futureloan/member/login', params='{"mobile_phone":"","pwd":"123456"}', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='null'}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [PASSED] but found [FAILED]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.lemon.cases.LoginCase.test(LoginCase.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="FAIL" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.LoginCase@3f19b8b3]" name="test" duration-ms="150" started-at="2020-08-14T20:51:44Z" data-provider="datas" finished-at="2020-08-14T20:51:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=3, name='login', method='post', url='http://api.lemonban.com/futureloan/member/login', params='{"mobile_phone":"123","pwd":"123456123"}', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='null'}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [PASSED] but found [FAILED]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.lemon.cases.LoginCase.test(LoginCase.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="FAIL" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.LoginCase@3f19b8b3]" name="test" duration-ms="133" started-at="2020-08-14T20:51:44Z" data-provider="datas" finished-at="2020-08-14T20:51:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=4, name='login', method='post', url='http://api.lemonban.com/futureloan/member/login', params='{"mobile_phone":"19000000000","pwd":"12345"}', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='null'}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [PASSED] but found [FAILED]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.lemon.cases.LoginCase.test(LoginCase.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="FAIL" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.LoginCase@3f19b8b3]" name="test" duration-ms="203" started-at="2020-08-14T20:51:45Z" data-provider="datas" finished-at="2020-08-14T20:51:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=5, name='login', method='post', url='http://api.lemonban.com/futureloan/member/login', params='{"mobile_phone":"13212332111","pwd":"12346567118"}', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='null'}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [PASSED] but found [FAILED]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.lemon.cases.LoginCase.test(LoginCase.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.LoginCase@3f19b8b3]" name="test" duration-ms="195" started-at="2020-08-14T20:51:45Z" data-provider="datas" finished-at="2020-08-14T20:51:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=6, name='login', method='post', url='http://api.lemonban.com/futureloan/member/login', params='{"mobile_phone":"17817620985","pwd":"12345678"}', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK","$.data.mobile_phone":"17817620985","$.data.type":1}', sql='null'}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- com.lemon.cases.LoginCase -->
    </test> <!-- 登录接口 -->
    <test name="用户信息" duration-ms="238" started-at="2020-08-14T12:51:45Z" finished-at="2020-08-14T12:51:45Z">
      <class name="com.lemon.cases.UserInfoCase">
        <test-method status="PASS" signature="beforeClass(int)[pri:0, instance:com.lemon.cases.UserInfoCase@21526f6c]" name="beforeClass" is-config="true" duration-ms="1" started-at="2020-08-14T20:51:45Z" finished-at="2020-08-14T20:51:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.UserInfoCase@21526f6c]" name="test" duration-ms="154" started-at="2020-08-14T20:51:45Z" description="用户信息测试" data-provider="datas" finished-at="2020-08-14T20:51:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=1, name='info', method='GET', url='http://api.lemonban.com/futureloan/member/2077205/info', params='null', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='null'}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- com.lemon.cases.UserInfoCase -->
    </test> <!-- 用户信息 -->
    <test name="充值接口" duration-ms="2158" started-at="2020-08-14T12:51:45Z" finished-at="2020-08-14T12:51:47Z">
      <class name="com.lemon.cases.RechargeCase">
        <test-method status="PASS" signature="beforeClass(int)[pri:0, instance:com.lemon.cases.RechargeCase@66971f6b]" name="beforeClass" is-config="true" duration-ms="0" started-at="2020-08-14T20:51:45Z" finished-at="2020-08-14T20:51:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.RechargeCase@66971f6b]" name="test" duration-ms="212" started-at="2020-08-14T20:51:45Z" data-provider="datas" finished-at="2020-08-14T20:51:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=1, name='recharge', method='post', url='http://api.lemonban.com/futureloan/member/recharge', params='{"member_id":"-1","amount":"6300"}', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='null'}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [PASSED] but found [FAILED]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.lemon.cases.RechargeCase.test(RechargeCase.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="FAIL" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.RechargeCase@66971f6b]" name="test" duration-ms="144" started-at="2020-08-14T20:51:46Z" data-provider="datas" finished-at="2020-08-14T20:51:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=2, name='recharge', method='post', url='http://api.lemonban.com/futureloan/member/recharge', params='{"member_id":"2077205","amount":"1116300"}', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='null'}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [PASSED] but found [FAILED]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.lemon.cases.RechargeCase.test(RechargeCase.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="FAIL" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.RechargeCase@66971f6b]" name="test" duration-ms="145" started-at="2020-08-14T20:51:46Z" data-provider="datas" finished-at="2020-08-14T20:51:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=3, name='recharge', method='post', url='http://api.lemonban.com/futureloan/member/recharge', params='{"member_id":"2077205","amount":"-6300"}', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='null'}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [PASSED] but found [FAILED]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.lemon.cases.RechargeCase.test(RechargeCase.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="FAIL" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.RechargeCase@66971f6b]" name="test" duration-ms="133" started-at="2020-08-14T20:51:46Z" data-provider="datas" finished-at="2020-08-14T20:51:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=4, name='recharge', method='post', url='http://api.lemonban.com/futureloan/member/recharge', params='{"member_id":"2077205","amount":"SSS"}', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='null'}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [PASSED] but found [FAILED]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.lemon.cases.RechargeCase.test(RechargeCase.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="FAIL" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.RechargeCase@66971f6b]" name="test" duration-ms="841" started-at="2020-08-14T20:51:46Z" data-provider="datas" finished-at="2020-08-14T20:51:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=5, name='recharge', method='post', url='http://api.lemonban.com/futureloan/member/recharge', params='{"member_id":"2077205","amount":"1.11"}', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK","$.data.id":2069116}', sql='select leave_amount from member a where id = 2077205;'}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [PASSED] but found [FAILED]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [PASSED] but found [FAILED]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.lemon.cases.RechargeCase.test(RechargeCase.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.RechargeCase@66971f6b]" name="test" duration-ms="614" started-at="2020-08-14T20:51:47Z" data-provider="datas" finished-at="2020-08-14T20:51:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=6, name='recharge', method='post', url='http://api.lemonban.com/futureloan/member/recharge', params='{"member_id":"2077205","amount":"5000"}', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK","$.data.id":2077205}', sql='select leave_amount from member a where id = 2077205;'}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- com.lemon.cases.RechargeCase -->
    </test> <!-- 充值接口 -->
    <test name="新增项目接口" duration-ms="223" started-at="2020-08-14T12:51:47Z" finished-at="2020-08-14T12:51:48Z">
      <class name="com.lemon.cases.AddCase">
        <test-method status="PASS" signature="beforeClass(int)[pri:0, instance:com.lemon.cases.AddCase@35d6ca49]" name="beforeClass" is-config="true" duration-ms="0" started-at="2020-08-14T20:51:47Z" finished-at="2020-08-14T20:51:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.AddCase@35d6ca49]" name="test" duration-ms="140" started-at="2020-08-14T20:51:47Z" data-provider="datas" finished-at="2020-08-14T20:51:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=1, name='add', method='post', url='http://api.lemonban.com/futureloan/loan/add', params='{ "member_id":2077205, "title":"报名 Java 全栈自动化课程", "amount":6300.00, "loan_rate":12.0, "loan_term":12, "loan_date_type":1, "bidding_days":5 }', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='null'}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- com.lemon.cases.AddCase -->
    </test> <!-- 新增项目接口 -->
    <test name="管理员登录接口" duration-ms="284" started-at="2020-08-14T12:51:48Z" finished-at="2020-08-14T12:51:48Z">
      <class name="com.lemon.cases.LoginCase">
        <test-method status="PASS" signature="beforeClass(int)[pri:0, instance:com.lemon.cases.LoginCase@cf65451]" name="beforeClass" is-config="true" duration-ms="0" started-at="2020-08-14T20:51:48Z" finished-at="2020-08-14T20:51:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[4]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.LoginCase@cf65451]" name="test" duration-ms="197" started-at="2020-08-14T20:51:48Z" data-provider="datas" finished-at="2020-08-14T20:51:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=1, name='login', method='post', url='http://api.lemonban.com/futureloan/member/login', params='{"mobile_phone":"14791355931","pwd":"12345678"}', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='null'}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- com.lemon.cases.LoginCase -->
    </test> <!-- 管理员登录接口 -->
    <test name="审核项目接口" duration-ms="128" started-at="2020-08-14T12:51:48Z" finished-at="2020-08-14T12:51:48Z">
      <class name="com.lemon.cases.AuditCase">
        <test-method status="PASS" signature="beforeClass(int)[pri:0, instance:com.lemon.cases.AuditCase@d78795]" name="beforeClass" is-config="true" duration-ms="1" started-at="2020-08-14T20:51:48Z" finished-at="2020-08-14T20:51:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.AuditCase@d78795]" name="test" duration-ms="66" started-at="2020-08-14T20:51:48Z" data-provider="datas" finished-at="2020-08-14T20:51:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=1, name='audit', method='PATCH', url='http://api.lemonban.com/futureloan/loan/audit', params='{ "loan_id": 205148, "approved_or_not": true }', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='null'}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- com.lemon.cases.AuditCase -->
    </test> <!-- 审核项目接口 -->
    <test name="投资接口" duration-ms="225" started-at="2020-08-14T12:51:48Z" finished-at="2020-08-14T12:51:48Z">
      <class name="com.lemon.cases.InvestCase">
        <test-method status="PASS" signature="beforeClass(int)[pri:0, instance:com.lemon.cases.InvestCase@22c86919]" name="beforeClass" is-config="true" duration-ms="0" started-at="2020-08-14T20:51:48Z" finished-at="2020-08-14T20:51:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[6]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.InvestCase@22c86919]" name="test" duration-ms="182" started-at="2020-08-14T20:51:48Z" data-provider="datas" finished-at="2020-08-14T20:51:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=1, name='invest', method='post', url='http://api.lemonban.com/futureloan/member/invest', params='{"member_id":2074960,"loan_id":205148,"amount":6300.00} ', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='null'}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- com.lemon.cases.InvestCase -->
    </test> <!-- 投资接口 -->
    <test name="管理员用户信息" duration-ms="329" started-at="2020-08-14T12:51:48Z" finished-at="2020-08-14T12:51:49Z">
      <class name="com.lemon.cases.UserInfoCase">
        <test-method status="PASS" signature="beforeClass(int)[pri:0, instance:com.lemon.cases.UserInfoCase@6ea1bcdc]" name="beforeClass" is-config="true" duration-ms="0" started-at="2020-08-14T20:51:48Z" finished-at="2020-08-14T20:51:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="test(com.lemon.pojo.CaseInfo)[pri:0, instance:com.lemon.cases.UserInfoCase@6ea1bcdc]" name="test" duration-ms="278" started-at="2020-08-14T20:51:48Z" description="用户信息测试" data-provider="datas" finished-at="2020-08-14T20:51:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CaseInfo{id=1, name='info', method='GET', url='http://api.lemonban.com/futureloan/member/2074960/info', params='null', contentType='json', expectedResult='{"$.code":0,"$.msg":"OK"}', sql='null'}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="finish()[pri:0, instance:com.lemon.cases.UserInfoCase@6ea1bcdc]" name="finish" is-config="true" duration-ms="380" started-at="2020-08-14T20:51:49Z" finished-at="2020-08-14T20:51:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finish -->
      </class> <!-- com.lemon.cases.UserInfoCase -->
    </test> <!-- 管理员用户信息 -->
  </suite> <!-- futureloan -->
</testng-results>
